name: Test - Build

on:
  push:
    branches:
      - "main"

env:
  GKE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GKE_ZONE: asia-south1
  IMAGE: test-services
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY_HOSTNAME: us.gcr.io
  APP_NAME: test-services

jobs:
  node-build-deploy:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_PRIVATE_KEY }}

      - name: set-up-cloud-sdk
        uses: google-github-actions/setup-gcloud@v0

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: configure-docker
        shell: bash
        run: |
          gcloud auth configure-docker

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: us.gcr.io/kubernetes-istio-gcp/test-services:$GITHUB_SHA
          cache-from: type=registry,ref=us.gcr.io/kubernetes-istio-gcp/test-services:buildcache
          cache-to: type=registry,ref=us.gcr.io/kubernetes-istio-gcp/test-services:buildcache,mode=max

      # - name: docker-build
      #   shell: bash
      #   run: |
      #     docker build -t "$REGISTRY_HOSTNAME/$GKE_PROJECT/test-services:$GITHUB_SHA" .

      # - name: publish-to-registry
      #   shell: bash
      #   run: |
      #     docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/test-services:$GITHUB_SHA


